Storage memory management
unyt-org/datex-core-js-legacy pull request #58
Opened 2024-01-21 02:09 UTC by benStre

Closes https://github.com/unyt-org/datex-core-js-legacy/issues/53

This PR implements a garbage collection system for the DATEX pointer storage.
This is a completely separate GC system from the runtime GC, and it is still a quite naive implementation, but it is essential for storage memory management.

The GC is not specific for a storage location, but works with all storage locations (Databases, local storage, indexed db) that implement the `StorageLocation` API. 
It works simultaneously across all storage locations.

*Background:*
When we assume that all eternal pointers exist for "eternity", we don't need any kind of autmatic storage management - pointers are added to the storage and updated, but never deleted. Before this PR, a developer could explicitly delete pointers from the storage, but they were not removed when they were no longer needed. This is a big problem for huge collections like maps and sets with lots of volatile, changing data (e.g. temporary log entries).

The basic idea for the new storage GC is to use a basic reference counting (RC) system.
 * If a pointer is still directly or indirectly referenced by a storage item (which is essentially an eternal value binding), it is guaranteed to be kept in the storage.
 * On the other hand, it can't be guaranteed that a pointer will be removed from storage once it is no longer accessible (e.g. when there is a circular reference). This is a fundamental problem of RC - in the future, we might switch to a different, more sophisticated GC algorithm

Addtional new features:
 * Both StorageWeakMap and StorageWeakSets are now supported (with some limitations: https://github.com/unyt-org/datex-core-js-legacy/issues/57)
 * `Datex.Storage.printSnapshot()` can be used for storage analyis and debugging

Initial storage allocations when running `Datex.Storage.printSnapshot()` in a new UIX base project:
![image](https://github.com/unyt-org/datex-core-js-legacy/assets/35869401/81cf711e-32b6-41fc-baa4-d27e0d32b8f2)

2024-01-21 02:12 UTC, benStre commented
@jonasstrehle this is a very essential part of the DATEX runtime - it would be great if you could also test it out with some eternal value examples in a UIX base project (`Datex.Storage.printSnapshot()` for verification)  - and also make sure this change does not break any existing projects (the probability is very low)

2024-01-23 08:10 UTC, jonasstrehle requested changes

2024-01-23 08:10 UTC, jonasstrehle commented on types/storage_set.ts
>  			promises.push(await Storage.removeItem(key));
`await` at Storage.removeItem should probably not be here

2024-01-23 23:02 UTC, jonasstrehle approved these changes

2024-01-24 10:21 UTC, merged